This branch will be used to nerf all ground support modifiers
GrenadierSchubes/Oak-Remade-MP pull request #102
Opened 2022-08-06 20:18 UTC by lolmemes369

changing sir support base from 0.3 to 0.

This very well could fix many issues. It is a big change so it will require testing.

With it being at 0, it means divisions will only get org damage and strength damage if no extra ground support modifiers are added.

honestly making cas/tacts more about strength damage is prob better. Having very minimal ground support modifiers and just replacing it with ground attack factor is prob better. 

It would make AA actually matter divisionally as it would protect ur units from losing equipment.

math behind air_cas_present = ground support 
           (1+modifiers) * air_cas_present  = X
           ((1 + modifiers)+X) * (base attack) = final stats
           
           EX.
           air_cas_present = 0.5 (50% ground support)
           base_attack = 300
           modifiers = 1 (100%)
           1+ modifiers = 2 (200%)      
           2 * 0.5 = X = 1
           
           (2 +1) *300 = 900
            ground support is scaling so the more modifiers the worse it gets

2022-08-07 04:51 UTC, Narizna commented
was ground support increasing division stat attack as a modifier, instead of just hitting org/str?

2022-08-07 16:56 UTC, lolmemes369 commented
> was ground support increasing division stat attack as a modifier, instead of just hitting org/str?
Yes. The formula posted is what I gathered from testing a bit. 

The minimum amount of ground support attack stats you can get is 30%. This is including no other modifiers. That means 30% extra attack.  More modifiers increase the effectiveness of the ground support stat.

Potentially you can get ground support modifiers up to 60%/80% and 100%-120% due to various ground support modifiers laying around. So far I see a cap of 39% from quick testing with like 1.6k+ cas. I have seen it go up to 50% though.

I'm not exactly sure how easily or possible is it to get the max ground support fulfilled. 

So if I use GBP and get advisors:  70% max planning + 10% infantry attack + 10% special forces attack + 10% attack = 100%

with 30% ground support that would be    (100% + 100%)*30% = 60% attack stats.

2022-08-08 14:09 UTC, Mookubooku commented on common/ideas/GER.txt
> -				air_cas_present_factor = 0.1
I think this should stay in for Germany.

2022-08-08 14:10 UTC, Mookubooku commented on common/ideas/romania.txt
> -				air_cas_present_factor = 0.1
I think this should stay in for Romania. This focus generally isn't taken until late-war, anyways.

2022-08-08 14:12 UTC, Mookubooku commented on common/technologies/air_doctrine.txt
> -		air_cas_present_factor = 0.15
This should be reduced (0.1?) but should remain. A lot of minors use this to get a slight buff.

2022-08-09 01:52 UTC, lolmemes369 commented on common/ideas/GER.txt
> -				air_cas_present_factor = 0.1
Anything other non combat modifier to replace is fine. I rather the air modifiers not buff combat modifiers as much.

2022-08-09 01:53 UTC, lolmemes369 commented on common/ideas/romania.txt
> -				air_cas_present_factor = 0.1
It is the same as the german one which is why it is removed.

2022-08-09 01:54 UTC, lolmemes369 commented on common/technologies/air_doctrine.txt
> -		air_cas_present_factor = 0.15
the Ground support is 15% total and BS gets other stuff. They can go a specific doctrine for ground support modifiers

2022-08-09 01:57 UTC, lolmemes369 commented on common/defines/00_defines.lua
> -	AIR_SUPPORT_BASE = 0.3,                        -- CAS bonus factor for air support moddifier for land unit in combat
Cas and red air is alrdy strong to incentives it. No other air modifiers are above 100%. I rather cas be strong through strength or org damage which it alrdy is. The ground support modifier just makes it way worse. 

The change is supposed to make air not end a front in 2 weeks. But Weaken the front over a longer period of time.

2022-08-11 21:47 UTC, Mookubooku commented on common/technologies/air_doctrine.txt
> -		air_cas_present_factor = 0.15
Battlefield Support _is_ the doctrine for ground support. If we're gutting the base ground support, we shouldn't touch this too much. Some land doctrines also give ground support.

2022-08-12 00:33 UTC, lolmemes369 commented on common/technologies/air_doctrine.txt
> -		air_cas_present_factor = 0.15
Yeah and now it is actually useful. Before it was actually useless since the extra 30% never really mattered. When fighting you only got up to 30% in most cases. I would be ok with buffing strength or air damage. 

15% is a lot. That is 15% stats not counting any other modifiers.  If you add planning or more modifiers it get better.

2022-09-02 05:08 UTC, Narizna commented
Coming back to this.

reviewing saves of recent games - ground support is maybe strong, but in actual game saves it seems to rarely get above what may be considered a "normal" modifier level. 

I think we could/should come back to this after targeting other parts of Air dominance issues.

2022-09-03 01:33 UTC, lolmemes369 commented
> Coming back to this.
> 
> reviewing saves of recent games - ground support is maybe strong, but in actual game saves it seems to rarely get above what may be considered a "normal" modifier level.
> 
> I think we could/should come back to this after targeting other parts of Air dominance issues.

It rarely goes above 30% which makes BFS a useless doctrine since the base is 30%.

2022-09-09 04:10 UTC, Narizna commented
I want to come back to this.

Could we perhaps only change the base ground support modifier? or do all these changes need to happen so nothing gets broken?

2022-09-09 19:37 UTC, Mookubooku commented
I'd like to see what only changing the base ground support (0.1?) and the temporary buffs for the German offensives (cac's proposed values seem fine) would do. I think we should keep the air spirits and doctrines the same for now.

2022-09-10 03:17 UTC, lolmemes369 commented
> I'd like to see what only changing the base ground support (0.1?) and the temporary buffs for the German offensives (cac's proposed values seem fine) would do. I think we should keep the air spirits and doctrines the same for now.

Basically the max possible (including from offensives) needs to be 30-40. I opted for 25 minus the offensives. 25 + offensives should equal 30-40.

2022-09-12 10:46 UTC, Mookubooku requested changes
I still think we should most change the base ground support and the offensives (values you have are fine. Air spirits and doctrines should be fine after that.

2022-09-16 04:24 UTC, Narizna approved these changes
So, I am actually inclined to agree with these changes - even if I believe they go a little far, I think getting a game or two should really give a lot of "intel" to how these changes affect the game. I can only do so many "tests" to a point where I need to see a real game experience.

2022-09-16 04:44 UTC, lolmemes369 commented
> So, I am actually inclined to agree with these changes - even if I believe they go a little far, I think getting a game or two should really give a lot of "intel" to how these changes affect the game. I can only do so many "tests" to a point where I need to see a real game experience.

I added bomber targeting to SD and OI. to compensate for the loss of GS. Not sure if that would be too op. 

SD: has BT 0.05 (idk what else to add to infrastructure destruction since Logistic strike is locked behind dlc)
OI: has BT 0.10

2022-09-21 16:51 UTC, GrenadierSchubes approved these changes
like the direction and changes.  Will approve however need to resolve conflicts

2022-09-21 19:28 UTC, GrenadierSchubes commented on common/defines/00_defines.lua
> -	AIR_SUPPORT_BASE = 0.3,                        -- CAS bonus factor for air support moddifier for land unit in combat
I have been playing a bit watching how ai does and so far i enjoy

2022-09-21 21:11 UTC, Mookubooku commented on common/ideas/GER.txt
> -				air_cas_present_factor = 0.1
Germany and Romania should get some kind of buff to replace this...

2022-09-21 21:11 UTC, Mookubooku commented on common/ideas/romania.txt
> -				air_cas_present_factor = 0.1
Germany and Romania should get some kind of buff to replace this...

2022-09-23 06:07 UTC, merged