Spy rework + arty terrain + tank designer fixes
GrenadierSchubes/Oak-Remade-MP pull request #127
Opened 2022-09-01 02:45 UTC by RH-131

2022-09-01 20:29 UTC, Mookubooku requested changes
Overall, looks really good. If this is the direction we want to take with the number of operatives (could be limiting, especially for minors), that's fine, but we should discuss before making changes. If there are solid LARP reasons why a tank designer gives inconsistent bonuses (e.g. tanks get +10% reliability but SPGs get -10%), that's fine too.

2022-09-01 20:29 UTC, Mookubooku commented on common/ideas/usa.txt
>  					reliability = -0.10
With the other tank designers, reliability was the same for a given tank designer. Is there a LARP reason for inconsistency here?

2022-09-01 20:29 UTC, Mookubooku commented on common/ideas/SOV.txt
>  					armor_value = 0.05
Armor value bonus should be -5%, not +5%.

2022-09-01 20:29 UTC, Mookubooku commented on common/ideas/SOV.txt
> +					maximum_speed = -0.1
Doesn't fit the pattern but OK for LARP.

2022-09-01 20:29 UTC, Mookubooku commented on common/defines/00_defines.lua
> +	MAX_OPERATIVE_SLOT_FROM_AGENCY_UPGRADES = 1,	-- max operative slots gained from upgrades
This will likely limit minor nations' ability to conduct operations.

2022-09-01 20:29 UTC, Mookubooku commented on common/ideas/GER.txt
>  			equipment_bonus = {
Should reliability for Daimler Benz should be -5% for all tank variants? Why just tanks and SPGs?

2022-09-01 20:29 UTC, Mookubooku commented on common/ideas/GER.txt
>  			equipment_bonus = {
Build cost IC increase should be consistent, probably 10% for SPGs and TDs as well.

2022-09-01 20:49 UTC, lolmemes369 commented on common/ideas/GER.txt
>  			equipment_bonus = {
> Build cost IC increase should be consistent, probably 10% for SPGs and TDs as well.

Because RH doesn't know what he is doing and just tried to "fix" my changes". I actually fixed some issues for the designer mainly IC cost.

2022-09-01 20:52 UTC, lolmemes369 commented on common/ideas/usa.txt
>  					reliability = -0.10
> With the other tank designers, reliability was the same for a given tank designer. Is there a LARP reason for inconsistency here?

RH doesn't know what he is doing. I try to keep the bonuses consistent.

2022-09-02 04:55 UTC, Narizna commented
+ for Arty changes
+ I don't do spy stuff much but I think it looks fair
= tank designers - I think it's ok, but I don't think it's answers the issue of imbalanced designers. mentioned more on discord.

2022-09-04 00:27 UTC, AnonymousRevan commented
> * plus for Arty changes
> * plus I don't do spy stuff much but I think it looks fair
> * meh tank designers - I think it's ok, but I don't think it answers the issue of imbalanced designers. mentioned more on discord.

I agree with Tuet's findings. I think for now the tank designers will do but will need changing in the future.

2022-09-04 00:27 UTC, AnonymousRevan approved these changes
tacit approval, see my comment

2022-09-04 02:23 UTC, Mookubooku approved these changes

2022-09-04 02:31 UTC, GrenadierSchubes approved these changes
reviewed and agreed with mooku changes

2022-09-04 02:31 UTC, merged