Annexed Philippines, removal of minor bomber IC reductions
GrenadierSchubes/Oak-Remade-MP pull request #130
Opened 2022-09-08 01:10 UTC by RH-131

2022-09-08 04:00 UTC, Narizna commented
so this is removing the IC reductions for bombers from various ideas instead of giving minors an IC cost debuff Idea? just want to clarify as I think the change in this PR is better than adding an idea.

2022-09-08 10:30 UTC, Mookubooku requested changes
Naval changes and USA annexing Philippines are fine. Needing minor plane production is not.

2022-09-08 13:55 UTC, GrenadierSchubes commented on common/ideas/romania.txt
> +					build_cost_ic = -0.12
why does romania now get 12% production cost bonus when all the minors were gutted?

2022-09-09 02:44 UTC, Ruling-0 commented
I have to agree with Mooku, and recommend making the plane IC changes it's own PR so it can be further discussed.

2022-09-09 05:44 UTC, closed without merging