Adding decision to annex mongolia 39
GrenadierSchubes/Oak-Remade-MP pull request #16
Opened 2022-04-19 01:58 UTC by GrenadierSchubes

Mongola annexation event 39

2022-04-19 03:34 UTC, Narizna commented
I have taken the stance a number of times in the past that mongolia should just be removed as a player.

it is arguably crutch for Russia if they don't have one
it is too powerful as an annexed nation for Russia

2022-04-19 03:49 UTC, Narizna requested changes

2022-04-19 03:49 UTC, Narizna commented on common/decisions/SOV.txt
> +			date > 1939.1.1
I would make 1941 and then would accept proposal

2022-04-19 11:25 UTC, iDealNimzi commented on common/decisions/SOV.txt
> +			date > 1939.1.1
that seems fair to try.

2022-04-19 11:26 UTC, iDealNimzi commented on common/decisions/SOV.txt
> +              transfer_troops = yes
I like the transfer_troops as well....

Is it possible to make this event available if 1 of the big cities fall?

2022-04-19 12:15 UTC, Mookubooku commented on common/decisions/SOV.txt
> +			date > 1939.1.1
I like the 1941 annex personally. We buffed Mongolia way more than it should be so a 1939 annex seems too strong unless we bring Mongolia's factory counts back down significantly.

2022-04-19 16:57 UTC, GrenadierSchubes reviewed
changed start date

2022-04-19 17:38 UTC, Ruling-0 approved these changes
Assuming this is tested

2022-04-19 17:42 UTC, iDealNimzi commented
Did this get tested?

2022-04-19 20:52 UTC, GrenadierSchubes commented
Testing works and localization is live

2022-04-19 23:03 UTC, Mookubooku approved these changes
1941 decision for SOV to annex MON looks good.

2022-04-20 15:00 UTC, GrenadierSchubes commented on common/decisions/SOV.txt
> +			date > 1939.1.1
Changed to 41 awaiting approval.

2022-04-20 20:29 UTC, lolmemes369 requested changes
I think the issue with annex builds and annexing Ai in general is that you start out with 100% compliance or can get it pretty easily. not exactly sure on the math. But the high compliance could make annex builds just better. This applies not just to the soviets but other nations. If 100% compliance makes up for annexing mongolia in 1941 and not having a player on it then the changes should be fine.

2022-04-20 21:24 UTC, GrenadierSchubes commented
Will come to discussion on annex build reduce compliance once axis are lowered as well.  For now they will all be the same.

2022-04-20 21:25 UTC, merged